get:
  operationId: listAllAssociatedWithUser
  tags:
    - Task
  description: List all tasks associated with authenticated user.
  security:
    - bearer: []
  responses:
    '200':
      description: OK
      content:
        'application/json':
          schema:
            $ref: '#components/schemas/TaskList'

post:
  operationId: createTask
  tags:
    - Task
  description: Create a new task
  security:
    - bearer: []
  requestBody:
    required: true
    content:
      'application/json':
        schema:
          $ref: '#components/schemas/TaskForm'
  responses:
    '201':
      description: New task is successfully created
      content:
        'application/json':
          schema:
            $ref: '#components/schemas/Task'
