#!/bin/sh

MIGRATIONS="$(realpath $(dirname $0))/../migrations"

migrate \
    -source="file://$MIGRATIONS" \
    -database="mysql://$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_DATABASE?parseTime=true" \
    $@
