// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasks)
	t.Run("Projects", testProjects)
	t.Run("Tasks", testTasks)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksDelete)
	t.Run("Projects", testProjectsDelete)
	t.Run("Tasks", testTasksDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksQueryDeleteAll)
	t.Run("Projects", testProjectsQueryDeleteAll)
	t.Run("Tasks", testTasksQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksSliceDeleteAll)
	t.Run("Projects", testProjectsSliceDeleteAll)
	t.Run("Tasks", testTasksSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksExists)
	t.Run("Projects", testProjectsExists)
	t.Run("Tasks", testTasksExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksFind)
	t.Run("Projects", testProjectsFind)
	t.Run("Tasks", testTasksFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksBind)
	t.Run("Projects", testProjectsBind)
	t.Run("Tasks", testTasksBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksOne)
	t.Run("Projects", testProjectsOne)
	t.Run("Tasks", testTasksOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksAll)
	t.Run("Projects", testProjectsAll)
	t.Run("Tasks", testTasksAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksCount)
	t.Run("Projects", testProjectsCount)
	t.Run("Tasks", testTasksCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksHooks)
	t.Run("Projects", testProjectsHooks)
	t.Run("Tasks", testTasksHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksInsert)
	t.Run("PlannedProjectTasks", testPlannedProjectTasksInsertWhitelist)
	t.Run("Projects", testProjectsInsert)
	t.Run("Projects", testProjectsInsertWhitelist)
	t.Run("Tasks", testTasksInsert)
	t.Run("Tasks", testTasksInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("PlannedProjectTaskToProjectUsingProject", testPlannedProjectTaskToOneProjectUsingProject)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ProjectToPlannedProjectTasks", testProjectToManyPlannedProjectTasks)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("PlannedProjectTaskToProjectUsingPlannedProjectTasks", testPlannedProjectTaskToOneSetOpProjectUsingProject)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ProjectToPlannedProjectTasks", testProjectToManyAddOpPlannedProjectTasks)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksReload)
	t.Run("Projects", testProjectsReload)
	t.Run("Tasks", testTasksReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksReloadAll)
	t.Run("Projects", testProjectsReloadAll)
	t.Run("Tasks", testTasksReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksSelect)
	t.Run("Projects", testProjectsSelect)
	t.Run("Tasks", testTasksSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksUpdate)
	t.Run("Projects", testProjectsUpdate)
	t.Run("Tasks", testTasksUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("PlannedProjectTasks", testPlannedProjectTasksSliceUpdateAll)
	t.Run("Projects", testProjectsSliceUpdateAll)
	t.Run("Tasks", testTasksSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
