// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PlannedProjectTasks string
	Projects            string
	Tasks               string
	Users               string
}{
	PlannedProjectTasks: "planned_project_tasks",
	Projects:            "projects",
	Tasks:               "tasks",
	Users:               "users",
}
