put:
  description: The Task is not done for the time being
  tags:
    - Task
  security:
    - bearer: []
  parameters:
    - $ref: '#components/parameters/TaskID'
  responses:
    '200':
      description: Accept
      content:
        'application/json':
          schema:
            $ref: '#components/schemas/Task'
