put:
  operationId: putOnHoldTask
  description: The Task will be put on hold for a while.
  tags:
    - Task
  security:
    - bearer: []
  parameters:
    - $ref: '#components/parameters/TaskID'
  responses:
    '200':
      description: Accept
      content:
        'application/json':
          schema:
            $ref: '#components/schemas/Task'
